version: '3.3'

services:
  images:
    build:
      context: ./images/python
      dockerfile: Dockerfile
    command: python3 ./stable/django/manage.py runserver 0.0.0.0:8083
    working_dir: /code
    volumes:
      - ".:/code"
    ports:
      - "8083:8083"

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf