version: '3.3'

services:
  # scala:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   working_dir: /code
  #   ports:
  #     - "9000:9000"
  #     - "9443:9443"
  #   volumes:
  #     - ".:/code"
  #   depends_on:
  #     - postgres
  #     - redis
  #   env_file:
  #     - .env

  postgres:
    container_name: postgres
    image: postgres:9.6.8
    ports:
      - "5432:5432"
    volumes:
      - ".:/code"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    env_file:
      - .env
  
  redis:
    image: redis:3.2.10
    ports:
      - "6379:6379"
    volumes:
      - ".:/code"
    command: redis-server --appendonly yes
    env_file:
      - .env

  # web:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./site.conf:/etc/nginx/conf.d/site.conf
  #   depends_on:
  #     - scala
  #   env_file:
  #     - .env