version: '3.3'

services:

  images:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./src/SMF2.1:/var/www/html/src
      - ./config/test/php:/var/www/html/test