version: '3.3'

services:
  images:
    build:
      context: ./images/me
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - ".:/code"

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf