version: '3.3'

services:

  images:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code/stable/vuejs
    volumes:
      - ".:/code"
    ports:
      - "38080:38080"
    env_file:
      - .env

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - images 