version: '3.3'

services:
  images:
    build:
      context: ./images/python
      dockerfile: Dockerfile
    command: python3 ./stable/django/django-crm/manage.py runserver 0.0.0.0:8083
    working_dir: /code
    volumes:
      - ".:/code"
    ports:
      - "8083:8083"
    depends_on:
      - postgres

  crm:
    image: lehungio/docker-images:django-crm
    command: python3 ./stable/django/django-crm/manage.py runserver 0.0.0.0:8084
    volumes:
      - .:/code
    ports:
      - "8084:8084"
    env_file:
      - .env

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - images

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env