version: '3.3'

services:

  php:
    image: lehungio/php-fpm:7.2
    restart: always
    working_dir: /code
    volumes:
      - ./:/code
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:5.7.17
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./:/code
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf