version: '3.3'

services:

  # jira:
  #   image: lehungio/infinity:jira
  #   volumes:
  #       - ./:/code

  jira_test:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    ports:
      - "7001:7001"
    volumes:
      - ".:/code"