# --- !Ups

CREATE TABLE IF NOT EXISTS people(
  -- "id" bigint generated by default as identity(start with 1) not null primary key,
  id                      BIGSERIAL       PRIMARY KEY,
  name                    VARCHAR(255) NOT NULL,
  age                     INT          NOT NULL
);

# --- !Downs

DROP TABLE IF EXISTS people;
